import re

with open('index.html', 'r', encoding='utf-8') as f:
    html = f.read()

# Descriptions in order for each section
major = [
    'Inicio, inocencia, libertad. El alma que se lanza al vac\u00edo sin mirar atr\u00e1s. Representa el esp\u00edritu libre que emprende un viaje sin mapa, confiando en el universo. Nos recuerda que cada gran aventura comienza con un salto de fe y que la verdadera sabidur\u00eda est\u00e1 en atreverse a ser vulnerable ante lo desconocido.',
    'Poder, habilidad, manifestaci\u00f3n. Canaliza la energ\u00eda divina hacia lo terrenal. El Mago domina los cuatro elementos y los dirige con voluntad consciente. Representa el momento en que reconoces tus talentos \u00fanicos y los pones al servicio de tu prop\u00f3sito, record\u00e1ndote que tienes todas las herramientas necesarias para crear tu realidad.',
    'Intuici\u00f3n, misterio, sabidur\u00eda interior. Guarda los secretos del inconsciente. Ella se sienta entre los pilares del conocimiento consciente y oculto, invit\u00e1ndote a mirar m\u00e1s all\u00e1 de lo evidente. Representa la conexi\u00f3n con tu voz interna, esa sabidur\u00eda silenciosa que emerge cuando aquietas la mente y escuchas los susurros del alma.',
    'Fertilidad, abundancia, naturaleza. La madre universal que nutre todo lo que crece. Ella encarna el poder creador de la naturaleza en su m\u00e1xima expresi\u00f3n. Te invita a conectarte con los ciclos de la vida, a florecer en tu propio tiempo y a recibir la abundancia que el universo tiene para ofrecerte cuando est\u00e1s en armon\u00eda con tu esencia.',
    'Autoridad, estructura, poder. El liderazgo y la solidez de las instituciones. Representa la fuerza yang, el padre protector que establece leyes y fronteras. Te llama a tomar el control de tu vida con disciplina y responsabilidad, construyendo cimientos s\u00f3lidos sobre los cuales puedas edificar tus sue\u00f1os m\u00e1s ambiciosos.',
    'Tradici\u00f3n, ense\u00f1anza, espiritualidad. El puente entre lo divino y lo humano. Es el guardi\u00e1n del conocimiento sagrado y las ense\u00f1anzas ancestrales. Te invita a buscar mentores, estudiar las tradiciones espirituales y encontrar la sabidur\u00eda en los rituales que conectan a la humanidad con lo trascendente a lo largo del tiempo.',
    'Amor, uni\u00f3n, elecci\u00f3n. La encrucijada del alma entre el deseo y el deber. No solo habla del amor rom\u00e1ntico sino de las decisiones cruciales que definen tu camino. Representa el momento de alinear tu coraz\u00f3n con tu prop\u00f3sito, eligiendo desde la autenticidad y sabiendo que cada decisi\u00f3n amorosa es un acto de valent\u00eda.',
    'Victoria, voluntad, determinaci\u00f3n. El triunfo sobre los opuestos internos. Guiado por la fuerza de voluntad, el auriga domina dos caballos que tiran en direcciones opuestas. Representa tu capacidad para superar obst\u00e1culos mediante la concentraci\u00f3n y la disciplina, avanzando hacia tus metas con la certeza de quien ha domado sus propias contradicciones.',
    'Fortaleza, coraje, compasi\u00f3n. El poder sereno de domar la bestia interior. No es la fuerza bruta sino el dominio tranquilo de los instintos primarios. Te recuerda que la verdadera fortaleza reside en la paciencia, la dulzura y la capacidad de enfrentar tus miedos con amor en lugar de agresi\u00f3n.',
    'Soledad, introspecci\u00f3n. La l\u00e1mpara que ilumina el camino interior. Lleva su luz en lo alto, buscando respuestas en el silencio de la monta\u00f1a. Te invita a retirarte del ruido exterior para encontrar la verdad dentro de ti, record\u00e1ndote que la sabidur\u00eda nace en la soledad elegida y se comparte desde la autenticidad.',
    'Destino, cambio, ciclos. La rueda c\u00f3smica que gira sin cesar. Nos recuerda que la vida es un ciclo constante de altibajos, \u00e9xitos y desaf\u00edos. Cuando aparece, se\u00f1ala que el cambio es inevitable y necesario, invit\u00e1ndote a fluir con las circunstancias porque lo que baja volver\u00e1 a subir y viceversa.',
    'Equilibrio, verdad, consecuencias. La balanza de la causa y el efecto. Ella no juzga desde el castigo sino desde la ecuanimidad m\u00e1s pura. Te llama a asumir la responsabilidad de tus actos, a buscar la verdad con honestidad y a restaurar el equilibrio en \u00e1reas de tu vida donde la balanza se ha inclinado.',
    'Sacrificio, rendici\u00f3n, nueva perspectiva. Ver el mundo desde otro \u00e1ngulo. Suspendido boca abajo, encuentra la paz en la entrega total. Representa el momento en que debes soltar el control, detener la resistencia y mirar la situaci\u00f3n desde una perspectiva radicalmente diferente para encontrar la soluci\u00f3n.',
    'Transformaci\u00f3n, renacimiento. El final de un ciclo y el nacimiento de lo nuevo. No es la muerte f\u00edsica sino la muerte de lo que ya no te sirve. Te invita a dejar ir relaciones, patrones o creencias que han caducado, confiando en que el vac\u00edo que dejan ser\u00e1 llenado por algo m\u00e1s aut\u00e9ntico y vivo.',
    'Equilibrio, moderaci\u00f3n, armon\u00eda. La fusi\u00f3n de los opuestos. El \u00e1ngel mezcla agua y fuego sin que ninguno extinga al otro. Representa la virtud de encontrar el punto medio, la paciencia para dejar que las cosas maduren y la maestr\u00eda de integrar las polaridades de tu ser en una danza arm\u00f3nica.',
    'Sombra, adicci\u00f3n. Enfrentar las cadenas que nos atamos a nosotros mismos. Representa las ataduras del mundo material, los vicios y las creencias limitantes que nos mantienen prisioneros. Te confronta con tu propia sombra para que reconozcas aquello que te esclaviza y encuentres la fuerza para liberarte.',
    'Caos, revelaci\u00f3n. El colapso que destruye ilusiones y abre paso a la verdad. Un rayo derriba la estructura m\u00e1s s\u00f3lida, revelando lo que estaba oculto. Aunque violenta, esta carta trae la liberaci\u00f3n que sigue a una crisis necesaria, derrumbando las falsas creencias para que puedas reconstruir desde cimientos m\u00e1s aut\u00e9nticos.',
    'Esperanza, inspiraci\u00f3n. La estrella que gu\u00eda hacia la sanaci\u00f3n y la paz. Despu\u00e9s de la tormenta de la Torre, llega la calma serena de la Estrella. Representa la renovaci\u00f3n de la fe, la conexi\u00f3n con tu prop\u00f3sito superior y la confianza en que el universo te sostiene en su manto de luz.',
    'Ilusi\u00f3n, miedo, subconsciente. Navegar las aguas profundas del inconsciente. Iluminada por una luz incierta, revela sombras y criaturas ocultas. Te advierte que no todo es lo que parece y te invita a explorar tus miedos m\u00e1s profundos, recordando que la oscuridad tambi\u00e9n contiene mensajes valiosos para tu evoluci\u00f3n.',
    'Alegr\u00eda, \u00e9xito, vitalidad. La carta m\u00e1s positiva: luz y plenitud. Disipa todas las sombras y revela la verdad en su m\u00e1xima expresi\u00f3n. Representa la alegr\u00eda sin condiciones, la confianza radiante y la celebraci\u00f3n de la vida. Te recuerda que mereces ser feliz y brillar con luz propia.',
    'Renacimiento, llamado superior. El despertar espiritual y la absoluci\u00f3n. Las trompetas anuncian un despertar, una llamada a elevarte hacia tu versi\u00f3n m\u00e1s elevada. Representa el momento de la rendici\u00f3n de cuentas contigo mismo, donde dejas atr\u00e1s el pasado y respondes al llamado de tu prop\u00f3sito m\u00e1s aut\u00e9ntico.',
    'Completitud, totalidad. La culminaci\u00f3n del viaje del alma. La \u00faltima carta del viaje simboliza la integraci\u00f3n de todas las lecciones aprendidas. Has completado un ciclo importante y te encuentras en un estado de plenitud y realizaci\u00f3n, listo para celebrar tus logros y prepararte para el pr\u00f3ximo gran ciclo.',
]

wands = [
    'Chispa divina, inspiraci\u00f3n, nuevo comienzo. El fuego creador que impulsa la acci\u00f3n. Representa el momento de la concepci\u00f3n de una idea, ese instante de claridad donde sientes el llamado a crear algo nuevo. Esta carta te anima a confiar en esa chispa interior y a dar el primer paso hacia lo que tu coraz\u00f3n anhela, porque el universo sostiene tu impulso inicial.',
    'Planificaci\u00f3n, visi\u00f3n, futuro. Mirar hacia adelante con poder y posesi\u00f3n. Sostienes el mundo en tus manos y contemplas horizontes lejanos. Representa el momento en que ya tienes una visi\u00f3n clara de lo que quieres y comienzas a planificar c\u00f3mo alcanzarlo. Te invita a salir de tu zona de confort y expandir tus l\u00edmites.',
    'Expansi\u00f3n, exploraci\u00f3n. El \u00e9xito que llega despu\u00e9s de la planificaci\u00f3n. Tus barcos han zarpado y observas el horizonte con confianza. Esta carta confirma que tus planes est\u00e1n dando frutos y que la expansi\u00f3n que buscabas est\u00e1 en marcha. Es el momento de mantener la fe y permitir que tus proyectos crezcan org\u00e1nicamente.',
    'Celebraci\u00f3n, armon\u00eda, hogar. La alegr\u00eda de los logros compartidos. Los pilares est\u00e1n firmes y bajo el arco de flores celebras tus \u00e9xitos. Representa la estabilidad alcanzada, el merecido descanso despu\u00e9s del esfuerzo y la alegr\u00eda de compartir tus triunfos con quienes amas. Es un recordatorio de celebrar cada paso del camino.',
    'Conflicto, competencia, desaf\u00edo. La lucha que forja el car\u00e1cter. Bastos entrecruzados en el aire, energ\u00edas que chocan en busca de direcci\u00f3n. Representa los conflictos inevitables del crecimiento, las diferencias de opini\u00f3n que ponen a prueba tu determinaci\u00f3n. Te invita a ver estos desaf\u00edos como oportunidades para fortalecer tu car\u00e1cter.',
    'Victoria, reconocimiento, confianza. El triunfo p\u00fablico y la admiraci\u00f3n. Regresas victorioso montado a caballo mientras las multitudes te aclaman. Esta carta trae el reconocimiento que has merecido por tu esfuerzo y dedicaci\u00f3n. Disfruta del \u00e9xito pero mantente humilde, recordando que el verdadero l\u00edder sirve a quienes lo siguen.',
    'Desaf\u00edo, defensa, perseverancia. Mantener la posici\u00f3n ante la adversidad. Desde lo alto defiendes tu terreno contra las cr\u00edticas y opositores. Representa la necesidad de mantener firmes tus convicciones cuando otros cuestionan tu camino. No se trata de atacar sino de proteger lo que has construido con integridad y valent\u00eda.',
    'Velocidad, movimiento, flechas del amor. La acci\u00f3n r\u00e1pida y el cambio. Bastos surcando el cielo en perfecta sincron\u00eda, imparable. Anuncia un per\u00edodo de avances r\u00e1pidos, comunicaciones repentinas y cambios que ocurren a gran velocidad. Prep\u00e1rate para recibir noticias y para actuar con rapidez aprovechando el impulso del momento.',
    'Resiliencia, \u00faltima defensa. La fuerza para seguir adelante a pesar del cansancio. Vendado y agotado, a\u00fan sostienes tu bast\u00f3n en posici\u00f3n de defensa. Representa la etapa final de una batalla larga, donde la perseverancia es tu \u00fanica arma. Te recuerda que la \u00faltima milla es la m\u00e1s dura pero tambi\u00e9n la que m\u00e1s te fortalece.',
    'Carga, responsabilidad, presi\u00f3n. El peso de las obligaciones. Agobiado por el peso de diez bastos, apenas puedes ver el camino. Representa las responsabilidades que has acumulado y que ahora te agotan. Te invita a evaluar qu\u00e9 cargas son realmente tuyas y cu\u00e1les puedes delegar o soltar antes de que el peso te derrumbe.',
    'Entusiasmo, exploraci\u00f3n, noticias. El mensajero del fuego creador. Joven y vibrante, contempla su bast\u00f3n con la mirada llena de posibilidades. Trae noticias emocionantes y el impulso de comenzar algo nuevo. Representa la energ\u00eda fresca del principiante que se lanza con pasi\u00f3n a explorar territorios desconocidos.',
    'Acci\u00f3n, aventura, pasi\u00f3n. El guerrero del fuego que cabalga hacia su destino. Montado a caballo con su bast\u00f3n en alto, avanza con determinaci\u00f3n ardiente. Representa la acci\u00f3n impulsiva y apasionada, la necesidad de moverse sin dudar. Te llama a perseguir tus metas con energ\u00eda imparable, pero cuidando no quemarte en el proceso.',
    'Calidez, determinaci\u00f3n, carisma. La madurez del fuego en su expresi\u00f3n m\u00e1s radiante. Ella irradia confianza y creatividad, su mirada segura inspira a quienes la rodean. Representa el dominio del fuego interior: pasi\u00f3n temperada por sabidur\u00eda, acci\u00f3n guiada por visi\u00f3n. Te invita a liderar con el ejemplo y a encender la chispa en otros.',
    'Liderazgo, visi\u00f3n, poder. El dominio del fuego y la autoridad natural. Sentado en su trono rodeado de llamas, el Rey de Bastos ha dominado el elemento del fuego. Representa al l\u00edder nato que inspira con su visi\u00f3n y valent\u00eda. Te llama a asumir tu poder con responsabilidad, a actuar con integridad y a encender el camino para quienes te siguen.',
]

cups = [
    'Amor, apertura emocional, nueva conexi\u00f3n. El manantial del coraz\u00f3n. Una copa dorada de la que fluye agua cristalina, ofreciendo amor incondicional. Representa el comienzo de una nueva etapa emocional, la apertura del coraz\u00f3n al amor y la conexi\u00f3n profunda. Te invita a recibir y dar afecto con la pureza del alma abierta.',
    'Uni\u00f3n, amor rec\u00edproco, conexi\u00f3n. El encuentro de dos almas. Dos copas elevadas en se\u00f1al de celebraci\u00f3n y reconocimiento mutuo. Representa las relaciones armoniosas, el amor que fluye en ambas direcciones y la asociaci\u00f3n basada en el respeto y la igualdad. Es la carta del amor correspondido y las alianzas sinceras.',
    'Celebraci\u00f3n, amistad, alegr\u00eda. La abundancia del coraz\u00f3n compartido. Tres mujeres elevan sus copas en una danza de gratitud y hermandad. Representa la alegr\u00eda de compartir con amigos, las celebraciones comunitarias y los momentos de felicidad colectiva. Te recuerda que la abundancia se multiplica cuando se comparte.',
    'Apat\u00eda, meditaci\u00f3n, oportunidades no vistas. La insatisfacci\u00f3n interior. Sentado bajo un \u00e1rbol, mira fijamente tres copas mientras una cuarta le es ofrecida desde el cielo. Representa el momento de estancamiento emocional donde no ves las oportunidades que se te presentan. Te invita a salir de la apat\u00eda y abrir los ojos a lo nuevo.',
    'P\u00e9rdida, duelo, arrepentimiento. Mirar atr\u00e1s con tristeza. Una figura con manto negro llora sobre tres copas derramadas mientras dos permanecen en pie detr\u00e1s. Representa el dolor de la p\u00e9rdida y la tendencia a enfocarse en lo que falta en lugar de lo que a\u00fan queda. Te recuerda que detr\u00e1s de toda p\u00e9rdida hay una oportunidad de renovaci\u00f3n.',
    'Nostalgia, recuerdos, inocencia. La pureza del pasado que reconforta. Dos ni\u00f1os en un jard\u00edn compartiendo flores, evocando la inocencia perdida. Representa los recuerdos felices, la nostalgia por tiempos pasados y las conexiones que te formaron. Te invita a honrar tu pasado sin quedarte atrapado en \u00e9l, extrayendo la dulzura sin el apego.',
    'Ilusiones, fantas\u00eda, elecciones. Las m\u00faltiples posibilidades del deseo. Siete copas flotando en el aire, cada una con una visi\u00f3n tentadora. Representa la confusi\u00f3n ante demasiadas opciones y el peligro de perderse en fantas\u00edas. Te advierte sobre las ilusiones que te distraen de tu camino verdadero y te pide claridad mental.',
    'Abandono, b\u00fasqueda, renuncia. Dejar atr\u00e1s lo conocido por lo desconocido. Una figura camina hacia la monta\u00f1a dejando atr\u00e1s ocho copas apiladas. Representa la valent\u00eda de abandonar lo seguro en busca de un prop\u00f3sito m\u00e1s elevado. Te llama a dejar atr\u00e1s lo que ya no te nutre espiritualmente, aunque duela.',
    'Satisfacci\u00f3n, abundancia emocional. El deseo cumplido y la felicidad plena. Sentado con los brazos cruzados y las nueve copas dispuestas en arco, sonr\u00ede satisfecho. Representa la realizaci\u00f3n de los deseos, la abundancia emocional y la satisfacci\u00f3n profunda. Es la carta de los sue\u00f1os cumplidos y la autoestima plena.',
    'Felicidad total, armon\u00eda familiar. La realizaci\u00f3n del amor incondicional. Una familia con los brazos alzados bajo un arco iris de diez copas celestiales. Representa la felicidad completa, la armon\u00eda en el hogar y el amor incondicional que trasciende generaciones. Es la promesa de un coraz\u00f3n pleno y un legado de amor.',
    'Intuici\u00f3n, sensibilidad, mensaje del coraz\u00f3n. El so\u00f1ador emocional. Joven con una copa de la que emerge un pez, s\u00edmbolo del mensaje del inconsciente. Trae noticias del coraz\u00f3n, inspiraci\u00f3n creativa y una invitaci\u00f3n a explorar tu mundo emocional. Representa la disposici\u00f3n a recibir la sabidur\u00eda de tus sue\u00f1os.',
    'Romance, imaginaci\u00f3n, propuesta. El caballero que sigue su coraz\u00f3n. Avanza lentamente con su copa en alto, ofreciendo amor y devoci\u00f3n. Representa la llegada de una propuesta rom\u00e1ntica, la b\u00fasqueda del ideal y la entrega sincera. Te invita a seguir tus sue\u00f1os con la misma pasi\u00f3n con la que este caballero persigue su visi\u00f3n.',
    'Empat\u00eda, curaci\u00f3n, amor incondicional. La madre del oc\u00e9ano emocional. Sentada en su trono junto al mar, contempla su copa decorada con \u00e1ngeles. Representa la sabidur\u00eda emocional madura, la capacidad de sanar a trav\u00e9s del amor y la comprensi\u00f3n profunda de los sentimientos ajenos. Te invita a liderar con el coraz\u00f3n.',
    'Madurez emocional, compasi\u00f3n. El dominio del mundo emocional. Flotando sobre el mar turbulento, sostiene firmemente su copa y su cetro. Representa el control sobre las emociones sin reprimirlas, la compasi\u00f3n equilibrada con sabidur\u00eda. Te llama a ser due\u00f1o de tu mundo interior, navegando las aguas emocionales con serenidad y madurez.',
]

swords = [
    'Claridad, verdad, ruptura. La espada de la mente que corta la ilusi\u00f3n. Una mano emerge de las nubes sosteniendo una espada vertical coronada por una corona. Representa el momento de la verdad absoluta, la claridad mental que disipa la confusi\u00f3n. Te llama a ver la realidad con honestidad, aunque duela, porque la verdad es la \u00fanica base s\u00f3lida para decidir.',
    'Decisi\u00f3n, punto muerto, bloqueo. La mente que no puede ver con claridad. Una figura vendada sostiene dos espadas cruzadas frente a su pecho. Representa la par\u00e1lisis por an\u00e1lisis y la dificultad para tomar una decisi\u00f3n. Te invita a quitarte la venda, a confiar en tu intuici\u00f3n y a enfrentar la elecci\u00f3n que has estado evadiendo.',
    'Dolor, traici\u00f3n, coraz\u00f3n herido. El sufrimiento que abre paso a la verdad. Tres espadas atraviesan un coraz\u00f3n en un cielo tormentoso. Representa el dolor emocional profundo, la traici\u00f3n o el desamor que parte el alma. Pero esta carta tambi\u00e9n trae el mensaje de que el dolor es temporal y que de toda herida nace una sabidur\u00eda m\u00e1s honda.',
    'Descanso, meditaci\u00f3n, recuperaci\u00f3n. La pausa necesaria para sanar. Una figura yacente con las manos en posici\u00f3n de oraci\u00f3n, tres espadas en la pared y una a su lado. Representa la necesidad de retirarte para recuperarte. Te invita a tomarte un descanso mental y emocional, confiando en que la pausa no es debilidad sino preparaci\u00f3n para renacer.',
    'Conflicto, derrota, tensi\u00f3n. La victoria vac\u00eda que deja heridas. Una figura sonr\u00ede mientras recoge tres espadas, dos m\u00e1s yacen en el suelo. Representa los conflictos donde nadie gana realmente, las peleas que dejan cicatrices. Te advierte sobre el costo de tener la raz\u00f3n a toda costa y te invita a elegir sabiamente tus batallas.',
    'Transici\u00f3n, viaje, dejar atr\u00e1s. Navegar hacia aguas m\u00e1s tranquilas. Una barca transporta seis espadas verticales mientras una figura empuja la embarcaci\u00f3n. Representa el viaje hacia un lugar mejor, dejando atr\u00e1s las turbulencias. Te asegura que despu\u00e9s de la tormenta llegar\u00e1 la calma, solo debes confiar en el movimiento hacia adelante.',
    'Enga\u00f1o, estrategia, sigilo. La mente astuta que busca su camino. Una figura hurta cinco espadas mientras dos quedan atr\u00e1s. Representa la necesidad de actuar con astucia, de pensar estrat\u00e9gicamente ante una situaci\u00f3n adversa. Te advierte sobre el enga\u00f1o externo pero tambi\u00e9n sobre tu propia capacidad de autoenga\u00f1o y te pide honestidad.',
    'Restricci\u00f3n, confusi\u00f3n, par\u00e1lisis. Las ataduras de la mente. Una figura vendada y atada rodeada de ocho espadas clavadas en la tierra. Representa la sensaci\u00f3n de estar atrapado sin salida. Pero las ataduras son sueltas y no hay paredes alrededor, solo tu mente te limita. Te invita a ver que las \u00fanicas cadenas son las que t\u00fa mismo te impones.',
    'Ansiedad, pesadillas, preocupaci\u00f3n. El peso de los miedos nocturnos. Una figura sentada en la cama con el rostro entre las manos, nueve espadas colgando sobre ella. Representa la angustia mental, las noches de insomnio y la tendencia a magnificar los problemas. Te recuerda que la oscuridad siempre antecede al amanecer y que tus miedos son menos poderosos de lo que parecen.',
    'Final, derrota, renacimiento. El fin doloroso que antecede al amanecer. Una figura yace atravesada por diez espadas mientras el horizonte se ilumina. Representa el final inevitable, la situaci\u00f3n que ha llegado a su t\u00e9rmino. Pero en la distancia, el sol comienza a salir. La derrota aparente es el preludio necesario para un nuevo comienzo.',
    'Vigilancia, ideas nuevas, curiosidad. El mensajero del viento mental. Joven alerta con la espada en alto, observando el horizonte en busca de conocimiento. Representa la mente despierta, la curiosidad intelectual y la disposici\u00f3n para aprender. Trae nuevas ideas, descubrimientos y la necesidad de comunicar lo que has comprendido.',
    'Determinaci\u00f3n, acci\u00f3n mental. El guerrero que corta con la espada de la verdad. Cabalga a toda velocidad con la espada en alto, listo para enfrentar cualquier desaf\u00edo. Representa la acci\u00f3n decidida basada en la verdad, la comunicaci\u00f3n directa y la defensa de tus principios. Te llama a actuar con valent\u00eda intelectual y a no retroceder ante la verdad.',
    'Claridad, independencia, sabidur\u00eda. La se\u00f1ora del aire que ve la verdad. Sentada en su trono adornado con \u00e1ngeles, sostiene su espada con firmeza. Representa la sabidur\u00eda ganada a trav\u00e9s de la experiencia y el dolor. Su mirada penetrante no tolera mentiras. Te invita a cortar lo que ya no sirve con la espada de la verdad y la compasi\u00f3n.',
    'Autoridad intelectual, \u00e9tica. El poder de la mente y la justicia. En su trono elevado entre las nubes, sostiene su espada firmemente. Representa la autoridad basada en la sabidur\u00eda, la justicia impartida con ecuanimidad y el poder de la mente clara. Te llama a tomar decisiones con l\u00f3gica y \u00e9tica, poniendo la verdad por encima de los intereses personales.',
]

pentacles = [
    'Creaci\u00f3n, prosperidad, nuevo ciclo. La semilla de la abundancia material. Una mano del cielo sostiene un gran oro del que brota un jard\u00edn. Representa el comienzo de una empresa material, una oportunidad financiera o el inicio de un proyecto concreto. Te invita a plantar las semillas de tu abundancia con confianza y dedicaci\u00f3n.',
    'Equilibrio, adaptaci\u00f3n, cambio. El malabarista que danza con la vida. Un hombre hace malabares con dos oros mientras el mar ondula a sus espaldas. Representa la necesidad de equilibrar m\u00faltiples responsabilidades y recursos. Te recuerda que la vida es un flujo constante y que tu habilidad para adaptarte determina tu \u00e9xito. Mant\u00e9n el equilibrio entre dar y recibir.',
    'Trabajo en equipo, maestr\u00eda, creaci\u00f3n. La colaboraci\u00f3n que construye. Tres personas trabajando juntas en la construcci\u00f3n de una catedral. Representa el poder de la colaboraci\u00f3n, la maestr\u00eda t\u00e9cnica y el fruto del trabajo en equipo. Te recuerda que las grandes obras no se logran en soledad y que cada uno aporta un don \u00fanico al proyecto com\u00fan.',
    'Estabilidad, control, ahorro. La seguridad de poseer y retener. Un hombre aferra cuatro oros protegi\u00e9ndolos celosamente. Representa la necesidad de seguridad material, el ahorro prudente y el control sobre los recursos. Pero tambi\u00e9n advierte sobre el apego excesivo al dinero y la tendencia a cerrarse por miedo a perder lo que tienes.',
    'Dificultad, p\u00e9rdida material. La prueba de la fe en tiempos de escasez. Dos figuras harapientas pasan frente a una iglesia iluminada sin entrar. Representa la p\u00e9rdida material, la exclusi\u00f3n y los momentos de escasez. Pero te recuerda que la ayuda est\u00e1 disponible si abres los ojos y pides apoyo, y que la verdadera riqueza reside en el esp\u00edritu.',
    'Generosidad, caridad, equilibrio. La justa distribuci\u00f3n de los recursos. Un hombre con balanza reparte monedas a dos mendigos. Representa la generosidad equilibrada, la caridad consciente y la justa distribuci\u00f3n de la riqueza. Te invita a dar y recibir con equidad, reconociendo que todos somos tanto maestros como aprendices en la danza de la abundancia.',
    'Evaluaci\u00f3n, paciencia, crecimiento. La cosecha que tarda en llegar. Un hombre observa su cosecha de oros colgados en un arbusto. Representa la evaluaci\u00f3n de tus inversiones y el fruto de tu trabajo paciente. Te invita a reflexionar sobre lo que has sembrado, a tener paciencia con los resultados y a decidir si continuar invirtiendo o cambiar de direcci\u00f3n.',
    'Dedicaci\u00f3n, aprendizaje, artesan\u00eda. La maestr\u00eda que nace del trabajo constante. Un artesano concentrado talla cada oro con esmero y dedicaci\u00f3n. Representa el aprendizaje meticuloso, la pr\u00e1ctica constante y el orgullo del trabajo bien hecho. Te recuerda que la maestr\u00eda no llega por inspiraci\u00f3n sino por la repetici\u00f3n consciente y el amor al oficio.',
    'Lujo, abundancia, autosuficiencia. La cosecha de los esfuerzos pasados. Una mujer rodeada de lujo en su jard\u00edn privado, con nueve oros dispuestos en arco. Representa la abundancia material alcanzada, la autosuficiencia y el disfrute de los frutos de tu trabajo. Te invita a celebrar tu \u00e9xito sin culpa y a compartir tu abundancia desde la plenitud.',
    'Legado, herencia, tradici\u00f3n. La riqueza que trasciende generaciones. Una familia reunida bajo un arco de diez oros que representa la prosperidad familiar. Habla de herencia, tradiciones familiares y el legado que construyes para las generaciones futuras. Te invita a honrar tus ra\u00edces mientras construyes un futuro s\u00f3lido para quienes vendr\u00e1n.',
    'Estudio, aplicaci\u00f3n, nuevo proyecto. El aprendiz del mundo material. Joven observa con atenci\u00f3n el oro que flota frente a \u00e9l, dispuesto a aprender. Representa el inicio de un proyecto pr\u00e1ctico, el estudio dedicado y la aplicaci\u00f3n paciente. Te anima a poner manos a la obra, a aprender haciendo y a valorar cada peque\u00f1o paso en tu formaci\u00f3n.',
    'Perseverancia, responsabilidad. El guardi\u00e1n paciente de la tierra. Montado en un caballo lento y pesado, sostiene su oro con firmeza. Representa la perseverancia, la responsabilidad y el trabajo constante. No es r\u00e1pido ni espectacular pero siempre llega a su destino. Te invita a avanzar paso a paso, confiando en que la constancia vence la resistencia.',
    'Abundancia, practicidad, nutrici\u00f3n. La madre tierra que provee y protege. En su trono rodeado de naturaleza, sostiene su oro con seguridad. Representa la abundancia pr\u00e1ctica, la capacidad de administrar los recursos con sabidur\u00eda y de nutrir tanto el cuerpo como el esp\u00edritu. Te invita a crear seguridad material sin perder la conexi\u00f3n con la tierra.',
    'Prosperidad, \u00e9xito, estabilidad. El se\u00f1or del mundo material realizado. Rodeado de todos los s\u00edmbolos de su \u00e9xito, el Rey de Oros ha alcanzado la cima del mundo material. Representa la prosperidad estable, la sabidur\u00eda financiera y el liderazgo empresarial. Te recuerda que el verdadero \u00e9xito incluye generosidad, responsabilidad y visi\u00f3n a largo plazo.',
]

all_descs = [
    ('major:', major),
    ('wands:', wands),
    ('cups:', cups),
    ('swords:', swords),
    ('pentacles:', pentacles),
]

# Process the HTML line by line
lines = html.split('\n')
new_lines = []
current_section = None
current_idx = 0

# Pattern to match desc:'...' or desc:"..." with possible escaped chars
desc_pattern = re.compile(r"(desc:'(?:[^'\\]|\\.)*')")

for line in lines:
    stripped = line.strip()
    
    # Check if this line starts a new section
    for section_key, desc_list in all_descs:
        if section_key in stripped and stripped.startswith(section_key):
            current_section = section_key
            current_idx = 0
            break
    
    # Check if this is a card data line
    if current_section and stripped.startswith('{num:'):
        # Find the section's desc list
        for section_key, desc_list in all_descs:
            if section_key == current_section:
                if current_idx < len(desc_list):
                    new_desc = desc_list[current_idx]
                    # Replace desc:'...' with desc:'new_desc'
                    line = re.sub(r"desc:'(?:[^'\\]|\\.)*'", "desc:'" + new_desc + "'", line)
                current_idx += 1
                break
    
    new_lines.append(line)

result = '\n'.join(new_lines)

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(result)

print('OK - descriptions updated')
